#ifndef E41A770B_4F39_453F_8EAF_C1FBC66AB950
#define E41A770B_4F39_453F_8EAF_C1FBC66AB950


#ifndef LOGGER_TIME_FORMAT
#define LOGGER_TIME_FORMAT "%Y-%m-%d %H:%M:%S"
#endif

#ifndef LOGGER_PREFIX_FORMAT
// #define LOGGER_PREFIX_FORMAT "{TIME} {USER_HEADER} {SERITY} {FILEINFO} {THREAD}"
#define LOGGER_PREFIX_FORMAT "{TIME} {USER_HEADER} {SERITY} {FILEINFO}"
#endif

#ifndef LOGGER_OUTFILE_NAME_FORMAT
#define LOGGER_OUTFILE_NAME_FORMAT "{EXE}"
#endif

#ifndef LOGGER_OUTFILE_FOLDER
#define LOGGER_OUTFILE_FOLDER "."
#endif


#endif
